### PR TITLE
Add ridedott/firestore-extensions

### PR DESCRIPTION
**Pull request by samtstern**
cc @merlinnnot

### CODE REVIEW

**Comment by merlinnot** [comment]
Is it possible for an organization to be an author?

**Comment by merlinnot** [comment]
That's ok, I wanted to give some recognition to other contributors as well, but I can see that there's a link to GitHub on the web page, everyone is featured there. Thanks!

**Comment by samtstern** [comment]
A project can also have multiple authors so I'd be happy to add more of
your co-workers to the site!

**Comment by merlinnot** [comment]
Awesome, I'll let everyone know so that they can choose for themselves if they want to be featured on the website.

**Pull request merged**
