### PR TITLE
Combine author profiles

### PR DESCRIPTION
**Pull request by gkindavishal**
Fixes b/273908804

### CODE REVIEW

**Comment by 5wathi** [comment]
LG @gkindavishal, but let's also remove the page from search! This came from the dev.

**Comment by gkindavishal** [comment]
> LG @gkindavishal, but let's also remove the page that has no content from search! This came from the dev.

Can you share which page you're referring to? @5wathi

**Comment by 5wathi** [comment]
Main author's page: https://devlibrary.withgoogle.com/authors/wal33d 

Merge this content to the above one and remove this page: https://devlibrary.withgoogle.com/authors/wal33d006

**Comment by gkindavishal** [comment]
@5wathi already updated that: https://github.com/google/devlibrary/pull/638/commits/a9f53f1dafa6b16b27109252bc2c5c28dbfa2641#diff-034cf51f4ed3aabdcf5ec0ff3666adcf1982ad8df5f39991cd989002e6107f49

**Pull request merged**
