### PR TITLE
Fix broken author images

### PR DESCRIPTION
**Pull request by barnesjoseph**
Adds dynamic author profile pictures (hashed background color with author initials).
Affected pages:
- /authors
- Individual author pages

### CODE REVIEW

**Comment by garimame** [comment]
@barnesjoseph Its showing the profile image for authors for which images are present on the page e.g. https://ugc-site-dev--pr447-fix-broken-author-im-zhwhd3o5.web.app/authors/deep-diver. Also I dont think the text color and background is as per guidelines ?

**Comment by barnesjoseph** [comment]
> 

I'm seeing the correct profile image at this link, can you send a screenshot of what you are seeing? What guidelines are you referring to? I'm using Google Material colors (500 for each color).

**Comment by barnesjoseph** [comment]
@garimame I have updated the colors/font to match a list of profile colors that I found. Let me know what you think. I couldn't replicate the issue that you were having with author images not showing up, I'm wondering if the page had cached previous changes that I made before I updated the code?

**Review by garimame — APPROVED** [review]
LGTM

**Pull request merged**
