### PR TITLE
Fix GitHub repo images

### PR DESCRIPTION
**Pull request by barnesjoseph**

### CODE REVIEW

**Comment by garimame** [comment]
@barnesjoseph This PR is not working for authors like this one https://ugc-site-dev--pr443-fix-github-repo-imag-0pt0tko3.web.app/authors/nagasainath.

**Comment by barnesjoseph** [comment]
@garimame This PR fixes this bug: b/243053030.
There is a separate bug to fix the author images issue, which I will work on soon: b/243049723

**Comment by garimame** [comment]
@barnesjoseph The preview links seems to have expired. Would you mind reopening it for quick testing?

**Comment by barnesjoseph** [comment]
> @barnesjoseph The preview links seems to have expired. Would you mind reopening it for quick testing?

The checks have be rerun, the preview link should work again.

**Review by garimame — APPROVED** [review]
LGTM

**Pull request merged**
