### PR TITLE
Removing the duplicate "Dmitry Efimenko" author

### PR DESCRIPTION
**Pull request by rodrigokamada**
Hi,

I am removing the duplicate "Dmitry A. Efimenko" and "Dmitry Efimenko" author.

I checked on https://devlibrary.withgoogle.com/authors that the  author is duplicate.

### CODE REVIEW

**Comment by samtstern** [comment]
Thanks for this! Could you do two things:

1) Update any project entries that use the deleted author ID to use the new one. 

2) Remove your author file from this PR, we'll merge it in the other one.

**Comment by rodrigokamada** [comment]
@samtstern I updated the new author reference.

Thanks!

**Comment by rodrigokamada** [comment]
@samtstern I forgot a reference. Now it's correct.

**Comment by samtstern** [comment]
Thank you!

**Pull request merged**
