### PR TITLE
Updated author details

### PR DESCRIPTION
**Pull request by RajashekarRaju**
- Made changes to author bio & mediumURL

### CODE REVIEW

**Comment by RajashekarRaju** [comment]
Please re-scan the current PR #298 , I have signed the CLA.

**Comment by samtstern** [comment]
CLA confirmed
Screen Shot 2022-01-07 at 10 31 29 AM

**Comment by samtstern** [comment]
Thanks @RajashekarRaju for contributing!

**Comment by RajashekarRaju** [comment]
> Thanks @RajashekarRaju for contributing!

Thank you :grinning: @samtstern for merging my first PR.

**Pull request merged**
